"""add post quantum provenance fields

Revision ID: 8dba97f9040d
Revises: 
Create Date: 2026-09-05 16:43:02.513559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dba97f9040d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('signature_algorithm', sa.String(length=50), nullable=True))
    op.add_column('dataset_versions', sa.Column('signature', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('provenance', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_versions', 'provenance')
    op.drop_column('dataset_versions', 'public_key')
    op.drop_column('dataset_versions', 'signature')
    op.drop_column('dataset_versions', 'signature_algorithm')
    # ### end Alembic commands ###
